// mova:engine
/**
 * The frame's two contracts, plus the promise newvisual.mjs makes.
 *
 * CONTRACT: a page generated by scripts/newvisual.mjs passes every gate in
 * scripts/visualcheck.mjs BEFORE any content is written. A skeleton that starts red
 * teaches the agent to ignore the gate, so this is the whole point of the generator and
 * not a nicety.
 *
 * The token expectation is DERIVED from visualcheck's CORE_TOKENS array rather than
 * retyped here — so adding a token to the gate fails this test until the frame defines it,
 * which is the direction the dependency should run.
 */
import { describe, it, expect, afterAll } from "vitest";
import { rmSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
// @ts-expect-error — untyped engine module
import { frame, page, STARTER } from "./visual-shell.mjs";
// @ts-expect-error — untyped engine module
import { CORE_TOKENS, checkPlayerCount, checkPlayerStyle, checkTokenBlock, checkFile } from "./visualcheck.mjs";

const built = () => page({ title: "contract page", sub: "fixture", body: "<p>x</p>" });

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
/**
 * The gate reads a real path — checkAnswerLeak shells out to leakcheck.mjs, and the hub-link
 * rule differs inside docs/visual/. So the fixture is written where a real page lives and
 * removed afterwards.
 */
const DATE = "0000-00-00";
const SLUG = "shell-contract-fixture";
const FIXTURE = join(root, `work/visuals/${DATE}_${SLUG}.html`);
afterAll(() => rmSync(FIXTURE, { force: true }));

describe("the page frame", () => {
  it("reads the pinned reference page, so there is one definition of the frame", () => {
    const { head, scripts } = frame();
    expect(STARTER).toBe("docs/visual/starter.html");
    expect(head).toContain("<style>");
    // Theme switcher, drill-surface modes, per-item reveal.
    expect(scripts.length).toBeGreaterThanOrEqual(3);
  });

  it("defines every CORE token in all three themes", () => {
    const html = built();
    for (const token of CORE_TOKENS) {
      const defs = [...html.matchAll(new RegExp(`${token}\\s*:`, "g"))].length;
      // bare :root, prefers-color-scheme, [data-theme="dark"], [data-theme="light"].
      expect(defs, `${token} is defined ${defs}× in the frame`).toBeGreaterThanOrEqual(4);
    }
    expect(checkTokenBlock(html)).toEqual([]);
  });

  it("carries all three theme blocks", () => {
    const html = built();
    expect(html).toMatch(/@media\s*\(prefers-color-scheme:\s*dark\)/);
    expect(html).toContain(`[data-theme="dark"]`);
    expect(html).toContain(`[data-theme="light"]`);
  });

  /**
   * The frame ships NO audio player. tts-embed.mjs owns it and injects it behind its own
   * marker; a second copy here would reintroduce, from the other direction, exactly the
   * duplication checkPlayerStyle exists to catch.
   */
  it("ships no audio player — neither script nor unscoped style", () => {
    const html = built();
    expect(html).not.toMatch(/getElementById\(\s*b\.dataset\.a\s*\)/);
    expect(checkPlayerCount(html)).toEqual([]);
    expect(checkPlayerStyle(html)).toEqual([]);
  });

  /**
   * …but it MAY carry scoped overrides. They need the player to exist; they do not define
   * it. Losing that distinction is how this check would start failing correct pages.
   */
  it("keeps the scoped drill-surface overrides", () => {
    const html = page({ title: "t", body: "<p>x</p>", vocab: true });
    expect(html).toContain(".vocab td.au .tts-row");
    expect(checkPlayerStyle(html)).toEqual([]);
  });

  it("points the hub link at the sibling hub, not up and out of docs/visual/", () => {
    const html = built();
    expect(html).toMatch(/<a class="tohub" href="index\.html"/);
    expect(html).not.toMatch(/href="\.\.\/\.\.\/work\/visuals\/index\.html"/);
  });

  it("marks a generated page as instance content, not engine", () => {
    expect(built()).toMatch(/^<!-- mova:instance -->/);
  });

  it("is self-contained — no external URL enters the frame", () => {
    const html = built();
    const refs = [...html.matchAll(/(?:src|href)\s*=\s*"([^"]+)"/g)].map((m) => m[1]);
    for (const r of refs) {
      expect(/^https?:|^\/\//.test(r), `external reference: ${r}`).toBe(false);
    }
  });

  /**
   * The promise newvisual.mjs makes, asserted end to end by RUNNING it: a generated page
   * passes EVERY gate before a word of content is added. Driving the real CLI rather than
   * calling page() with a hand-written body is deliberate — the skeleton's content (the
   * beat placeholders, and the .src verification note a fact-asserting table requires) is
   * part of the promise, and a test that supplies its own body would not check it.
   *
   * If this breaks, a new page now starts red — and an agent that sees the gate fail on an
   * untouched skeleton learns to stop reading it.
   */
  for (const [label, args] of [["plain", []], ["with the drill surface", ["--vocab"]]] as [string, string[]][]) {
    it(`passes every visualcheck gate, ${label}, with no content written`, () => {
      rmSync(FIXTURE, { force: true });
      execFileSync("node", [join(root, "scripts/newvisual.mjs"), SLUG, "--date", DATE, ...args], {
        cwd: root, stdio: "pipe",
      });
      expect(checkFile(FIXTURE, { pack: null })).toEqual([]);
    });
  }
});
